# Generated by Django 6.0.7 on 2026-07-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_site_deliverychallan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallan',
            name='assets',
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
