# Generated by Django 6.0.7 on 2026-07-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_deliverychallan_assets_deliverychallan_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_challans', to='assets.site'),
        ),
    ]
