# Generated by Django 6.0.7 on 2026-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_deliverychallan_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='verification_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
