# Generated by Django 6.0.7 on 2026-08-09 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenant_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('condition_type', models.CharField(choices=[('threshold', 'Threshold'), ('schedule', 'Schedule')], max_length=10)),
                ('metric', models.CharField(choices=[('purchase_needs_attention_count', 'Purchase bills needing attention'), ('purchase_unpaid_count', 'Unpaid purchase bills'), ('contracts_expiring_count', 'Contracts expiring within 30 days'), ('operational_digest', 'Daily operational digest')], max_length=40)),
                ('operator', models.CharField(blank=True, choices=[('gt', 'is more than'), ('gte', 'is at least'), ('lt', 'is less than'), ('lte', 'is at most')], default='', max_length=3)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('was_firing', models.BooleanField(default=False)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], default='telegram', max_length=10)),
                ('message_template', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'alerts_rule',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'is_active', 'condition_type'], name='alerts_rule_tenant__88f54d_idx')],
            },
        ),
    ]
