"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Download, Trash2 } from "@bop/icons";
import { formatDateTime } from "@/lib/inventory-constants";
import { Button } from "@bop/ui/components/button";
import { deleteDCAction } from "./actions";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@bop/ui/components/table";
import { Badge } from "@bop/ui/components/badge";

export function DCTable({
  dcs,
}: {
  dcs: {
    id: string;
    dc_number: string;
    dc_type: string;
    site: { name: string };
    generated_by: string;
    created_at: string;
    pdf_url: string;
  }[];
}) {
  const router = useRouter();
  const [deletingId, setDeletingId] = useState<string | null>(null);

  async function handleDelete(id: string) {
    if (!confirm("Are you sure you want to delete this Delivery Challan?")) return;
    setDeletingId(id);
    try {
      const res = await deleteDCAction(id);
      if (!res.success) {
        alert("Failed to delete DC: " + res.error);
      } else {
        router.refresh();
      }
    } finally {
      setDeletingId(null);
    }
  }

  if (dcs.length === 0) {
    return (
      <div className="flex h-40 flex-col items-center justify-center rounded-lg border border-dashed border-border bg-card/50 text-center">
        <p className="text-sm font-medium text-foreground">No Delivery Challans generated yet</p>
        <p className="mt-1 text-xs text-muted-foreground">
          Click the Generate DC button to create your first one.
        </p>
      </div>
    );
  }

  return (
    <div className="overflow-hidden rounded-md border border-border">
      <Table>
        <TableHeader className="bg-muted/50">
          <TableRow>
            <TableHead>DC Number</TableHead>
            <TableHead>Site</TableHead>
            <TableHead>Type</TableHead>
            <TableHead>Generated By</TableHead>
            <TableHead>Date</TableHead>
            <TableHead className="text-right">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {dcs.map((dc) => (
            <TableRow key={dc.id}>
              <TableCell className="font-medium">{dc.dc_number}</TableCell>
              <TableCell>{dc.site?.name || "-"}</TableCell>
              <TableCell>
                <Badge variant="outline">
                  {dc.dc_type === "returnable" ? "Returnable" : "Non-Returnable"}
                </Badge>
              </TableCell>
              <TableCell className="text-muted-foreground">{dc.generated_by}</TableCell>
              <TableCell className="text-muted-foreground">
                {formatDateTime(dc.created_at)}
              </TableCell>
              <TableCell className="text-right space-x-2">
                <a
                  href={dc.pdf_url}
                  download
                  className="inline-flex h-8 items-center justify-center rounded-md bg-secondary px-3 text-xs font-medium text-secondary-foreground shadow-sm hover:bg-secondary/80 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                >
                  <Download className="mr-2 h-3.5 w-3.5" />
                  Download PDF
                </a>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8 text-destructive hover:bg-destructive/10"
                  disabled={deletingId === dc.id}
                  onClick={() => handleDelete(dc.id)}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
