# Generated by Django 6.0.7 on 2026-07-24 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenant_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webhook', 'Webhook'), ('manual', 'Manual upload')], max_length=10)),
                ('external_id', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('mapped_module', models.CharField(blank=True, default='', max_length=50)),
                ('mapped_object_type', models.CharField(blank=True, default='', max_length=100)),
                ('mapped_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'identity_source_identity',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'channel', 'external_id'], name='identity_so_tenant__c73835_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'channel', 'external_id'), name='uniq_identity_per_channel')],
            },
        ),
    ]
