# Generated by Django 6.0.7 on 2026-07-24 04:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenancy", "0002_tenant_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("pipeline_key", models.CharField(db_index=True, max_length=100)),
                ("pipeline_version", models.PositiveIntegerField(default=1)),
                ("step_keys", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("compensating", "Compensating"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=13,
                    ),
                ),
                (
                    "termination_reason",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("failed", "Failed"), ("cancelled", "Cancelled")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("current_step_index", models.PositiveIntegerField(default=0)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("schedule", "Schedule"),
                            ("manual", "Manual"),
                            ("event", "Event"),
                        ],
                        default="schedule",
                        max_length=10,
                    ),
                ),
                ("source_module", models.CharField(blank=True, default="", max_length=50)),
                ("source_object_type", models.CharField(blank=True, default="", max_length=100)),
                ("source_object_id", models.CharField(blank=True, default="", max_length=64)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=200)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pipeline_run",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PipelineStepRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("step_index", models.PositiveIntegerField()),
                ("step_key", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("compensating", "Compensating"),
                            ("compensated", "Compensated"),
                            ("compensation_failed", "Compensation failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflow.pipelinerun",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "pipeline_step_run",
                "ordering": ["step_index"],
            },
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["tenant", "status", "pipeline_key"], name="pipeline_ru_tenant__0ebc3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["tenant", "source_module", "source_object_type", "source_object_id"],
                name="pipeline_ru_tenant__5cce1d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinerun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("tenant", "pipeline_key", "idempotency_key"),
                name="uniq_pipeline_run_idempotency",
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinesteprun",
            index=models.Index(
                fields=["status", "locked_at"], name="pipeline_st_status_a240e0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinesteprun",
            constraint=models.UniqueConstraint(
                fields=("run", "step_index"), name="uniq_pipeline_step_run_index"
            ),
        ),
    ]
