# Generated by Django 6.0.7 on 2026-07-24 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenant_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('closing', 'Closing'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'periods_business_period',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_counts', models.JSONField(blank=True, default=dict)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manifest', to='periods.businessperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'periods_manifest',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='businessperiod',
            index=models.Index(fields=['tenant', 'year', 'month'], name='periods_bus_tenant__de6776_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'year', 'month'), name='uniq_period_per_tenant'),
        ),
    ]
