# Generated by Django 6.0.7 on 2026-07-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='document',
            name='reviewed_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
    ]
