# Generated by Django 6.0.7 on 2026-07-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_tags_to_tagging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('contract', 'Contract'), ('invoice', 'Invoice'), ('policy', 'Policy'), ('po', 'PO'), ('report', 'Report'), ('purchase_bill', 'Purchase Bill'), ('correspondence', 'Correspondence'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
