# Generated by Django 6.0.7 on 2026-07-21 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('index', models.CharField(max_length=50)),
                ('doc_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('url', models.CharField(blank=True, default='', help_text='Frontend route for this result, e.g. /purchases/bills/<id>.', max_length=300)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'search_document',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'index'], name='search_docu_tenant__e8171c_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'index', 'doc_id'), name='uniq_search_doc_per_index')],
            },
        ),
    ]
