# Generated by Django 6.0.7 on 2026-07-20 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'purchase_vendor',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('seller_name', models.CharField(max_length=200)),
                ('purchase_date', models.DateField()),
                ('total_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('document_url', models.URLField(max_length=500)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('source_channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('upload', 'Manual upload')], default='telegram', max_length=20)),
                ('raw_extraction', models.JSONField(blank=True, default=dict, help_text='The full OCR/extraction payload, kept for audit and reprocessing.')),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='purchase.vendor')),
            ],
            options={
                'db_table': 'purchase_bill',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_vendor_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['tenant', 'status'], name='purchase_bi_tenant__f9b153_idx'),
        ),
    ]
