# Generated by Django 6.0.7 on 2026-07-20 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GSTIN, if the vendor is GST-registered.', max_length=15),
        ),
        migrations.AddIndex(
            model_name='purchasebill',
            index=models.Index(fields=['tenant', 'payment_status'], name='purchase_bi_tenant__73840b_idx'),
        ),
    ]
