# Generated by Django 6.0.7 on 2026-07-21 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchasebill_paid_at_purchasebill_payment_status_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='external_ref',
            field=models.CharField(blank=True, default='', help_text='Stable id of the source document (e.g. Telegram file_unique_id). Ingestion dedupes on it; blank means the channel had none.', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='purchasebill',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref', ''), _negated=True), fields=('tenant', 'source_channel', 'external_ref'), name='uniq_bill_external_ref_per_channel'),
        ),
    ]
