# Generated by Django 6.0.7 on 2026-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchasebill_external_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='Extracted line items: [{item_name, quantity, unit_price, tax, total}]'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='storage_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('needs_attention', 'Needs Attention')], db_index=True, default='processed', max_length=20),
        ),
    ]
