# Generated by Django 6.0.7 on 2026-07-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_purchasebill_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
