# Generated by Django 6.0.8 on 2026-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0006_purchasebill_cgst_purchasebill_igst_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebill",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                db_index=True,
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
