# Generated by Django 6.0.7 on 2026-07-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='reorder_level',
        ),
    ]
