# Generated by Django 6.0.7 on 2026-07-26 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_leavetype_leaverequest_leavebalance_and_more'),
        ('tenancy', '0002_tenant_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geo_accuracy_m', models.FloatField(blank=True, null=True)),
                ('within_geofence', models.BooleanField(default=False)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, choices=[('in', 'In'), ('out', 'Out')], default='', max_length=3)),
                ('decision', models.CharField(choices=[('auto_approved', 'Auto approved'), ('flagged', 'Flagged for review'), ('rejected', 'Rejected')], max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_logs', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hr_punch_log',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['employee', 'captured_at'], name='hr_punch_lo_employe_b0d55d_idx'), models.Index(fields=['tenant', 'decision'], name='hr_punch_lo_tenant__6875d5_idx')],
            },
        ),
    ]
