# Generated by Django 6.0.7 on 2026-07-26 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_punchlog'),
        ('storage', '0002_storedfile_is_library_storedfile_period_month_and_more'),
        ('tenancy', '0002_tenant_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('workflow', models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], default='onboarding', max_length=20)),
                ('default_due_days', models.IntegerField(default=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hr_task_template',
                'ordering': ('workflow', 'sort_order'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('workflow', models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], default='onboarding', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hr.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tasks', to='hr.tasktemplate')),
            ],
            options={
                'db_table': 'hr_employee_task',
                'ordering': ('due_date', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('financial_year', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('declared_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='hr.employee')),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_tax_declarations', to='storage.storedfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hr_tax_declaration',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expense_date', models.DateField()),
                ('amount', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Accommodation', 'Accommodation'), ('Office Supplies', 'Office supplies'), ('Medical', 'Medical'), ('Other', 'Other')], default='Other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_expense_decisions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_claims', to='hr.employee')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_expense_claims', to='storage.storedfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hr_expense_claim',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['employee', 'expense_date'], name='hr_expense__employe_9ce1d6_idx'), models.Index(fields=['tenant', 'status'], name='hr_expense__tenant__ec3779_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['tenant', 'workflow', 'is_active'], name='hr_task_tem_tenant__70147a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetask',
            index=models.Index(fields=['employee', 'workflow'], name='hr_employee_employe_241abe_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetask',
            index=models.Index(fields=['tenant', 'status'], name='hr_employee_tenant__fc5c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxdeclaration',
            index=models.Index(fields=['employee', 'financial_year'], name='hr_tax_decl_employe_cd3435_idx'),
        ),
    ]
