# Generated by Django 6.0.8 on 2026-09-22 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_tasktemplate_employeetask_taxdeclaration_and_more'),
        ('storage', '0002_storedfile_is_library_storedfile_period_month_and_more'),
        ('tenancy', '0002_tenant_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nature_of_work',
            field=models.CharField(blank=True, default='Operation & Maintenance (STP)', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HRMSUploadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('version', models.PositiveIntegerField()),
                ('client_code', models.CharField(default='167948248', max_length=50)),
                ('attendance_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_uploads_generated', to=settings.AUTH_USER_MODEL)),
                ('stored_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_upload_attendance_files', to='storage.storedfile')),
                ('stored_hrms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_upload_hrms_files', to='storage.storedfile')),
                ('stored_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_upload_leave_files', to='storage.storedfile')),
                ('stored_paysheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_upload_paysheet_files', to='storage.storedfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hr_hrms_upload_log',
                'ordering': ('-year', '-month', '-version'),
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'year', 'month'], name='hr_hrms_upl_tenant__c12eb0_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'year', 'month', 'version'), name='uniq_hrms_upload_version_per_month')],
            },
        ),
    ]
