# Generated by Django 6.0.7 on 2026-07-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='is_library',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='period_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storedfile',
            name='period_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
