# Generated by Django 6.0.7 on 2026-07-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='reviewed_at',
        ),
    ]
