# Generated by Django 6.0.7 on 2026-07-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
