# Generated by Django 6.0.8 on 2026-08-15 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_auth', '0003_facecredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facecredential',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.AddField(
            model_name='facecredential',
            name='label',
            field=models.CharField(default='Face Profile', max_length=100),
        ),
        migrations.AlterField(
            model_name='facecredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
