# Generated by Django 6.0.7 on 2026-07-26 17:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0002_storedfile_is_library_storedfile_period_month_and_more'),
        ('tenancy', '0002_tenant_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('facility', models.CharField(blank=True, default='', max_length=255)),
                ('gstin', models.CharField(blank=True, default='', max_length=20)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('is_sez', models.BooleanField(default=False, help_text='SEZ sites are billed under IGST; everyone else under CGST + SGST.')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'finance_customer',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_type', models.CharField(choices=[('amc', 'AMC'), ('sales', 'Sales')], max_length=10)),
                ('number', models.CharField(max_length=60)),
                ('financial_year', models.CharField(max_length=9)),
                ('sequence_number', models.PositiveIntegerField()),
                ('invoice_date', models.DateField()),
                ('consignee_name', models.CharField(max_length=200)),
                ('consignee_address', models.TextField(blank=True, default='')),
                ('facility', models.CharField(blank=True, default='', max_length=255)),
                ('gstin', models.CharField(blank=True, default='', max_length=20)),
                ('is_sez', models.BooleanField(default=False)),
                ('tax_mode', models.CharField(choices=[('cgst_sgst', 'CGST + SGST'), ('igst', 'IGST')], max_length=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('period_year', models.PositiveIntegerField(blank=True, null=True)),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('period_text', models.CharField(blank=True, default='', max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_in_words', models.CharField(blank=True, default='', max_length=400)),
                ('local_path', models.CharField(blank=True, default='', max_length=500)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.customer')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_invoices', to='storage.storedfile')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'finance_invoice',
                'ordering': ('-invoice_date', '-sequence_number'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=500)),
                ('hsn', models.CharField(blank=True, default='', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('uom', models.CharField(blank=True, default='Nos', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice')),
            ],
            options={
                'db_table': 'finance_invoice_line',
                'ordering': ('position',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('financial_year', models.CharField(max_length=9)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'finance_invoice_sequence',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'name'), name='uniq_finance_customer_name'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'invoice_type'], name='finance_inv_tenant__d52834_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'invoice_date'], name='finance_inv_tenant__124645_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'financial_year', 'sequence_number'), name='uniq_finance_invoice_sequence'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_finance_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoicenumbersequence',
            constraint=models.UniqueConstraint(fields=('tenant', 'financial_year'), name='uniq_finance_sequence_per_year'),
        ),
    ]
