# Generated by Django 6.0.7 on 2026-07-26 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('storage', '0002_storedfile_is_library_storedfile_period_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_invoice_pdfs', to='storage.storedfile'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_local_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revision',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='issued', max_length=10),
        ),
    ]
