# Generated by Django 6.1 on 2026-08-29 12:44

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_invoice_due_date_invoice_paid_at_and_more"),
        ("storage", "0002_storedfile_is_library_storedfile_period_month_and_more"),
        ("tenancy", "0002_tenant_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="source",
            field=models.CharField(
                choices=[("generated", "Generated"), ("imported", "Imported")],
                db_index=True,
                default="generated",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finance_invoice_sources",
                to="storage.storedfile",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("review", "In review"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="processing",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "finance_invoice_import_batch",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceImportItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("extracted", "Ready to review"),
                            ("needs_attention", "Needs attention"),
                            ("committed", "Committed"),
                            ("failed", "Failed"),
                            ("discarded", "Discarded"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("raw_extraction", models.JSONField(blank=True, default=dict)),
                ("proposed", models.JSONField(blank=True, default=dict)),
                (
                    "proposed_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("proposed_invoice_date", models.DateField(blank=True, null=True)),
                (
                    "proposed_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=4
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("run_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.invoiceimportbatch",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_items",
                        to="finance.invoice",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_import_items",
                        to="storage.storedfile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "finance_invoice_import_item",
                "ordering": ("created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="finance_inv_tenant__784151_idx",
                    ),
                    models.Index(
                        fields=["tenant", "batch"],
                        name="finance_inv_tenant__e0f8bc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("tenant", "batch", "content_hash"),
                        name="uniq_finance_import_item_hash",
                    )
                ],
            },
        ),
    ]
